version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aspectj
  - aspectjrt
  - codehaus
  - jquery
  - lantoolblog
  - logback
  - projectlombok
  - ultraq
  - webjars
  - webmvc
  - Xlint
ignoreWords: []
import: []
